viaacode/avo2-components

- .gitignore
- package-lock.json
- package.json
- src/components/RadioButton/RadioButton.tsx
Allows you to see which packages are taking up space in the final bundle.js
to run:
```
npm run build:with-sourcemaps
npm run analyze
```
result:
> feat: analyse bundle size

- src/components/ContentBlocks/BlockVideoTitleTextButton/BlockVideoTitleTextButton.test.tsx
- src/components/ContentBlocks/BlockVideoTitleTextButton/BlockVideoTitleTextButton.tsx
- src/components/Grid/Column.test.tsx
- src/components/Grid/Column.tsx
grid column widths work as follows:
* size 1 to 12 => are applied across all media queries
* size bp2-1 - bp1-12 => are applied on devices larger than 300px
* size bp2-1 - bp2-12 => are applied on devices larger than 600px
* size bp3-1 - bp3-12 => are applied on devices larger than 900px
if a device is encountered that is smaller than those indicated widths, the column will default to 100% wide
for the purpose of this pr i didn't have to change the column component to accept multiple sizes, but it might be useful in the future if we want to show for instance: 6 columns on desktop, 3 on tablet and 2 on mobile
The column still accepts a single size as it used it, so nothing will break.
> fix: allow columns with multiple size classes + fix content block size

- src/components/ImageGrid/ImageGrid.scss
> fix: make image grid border more pronounces + don't change image size

- src/components/MultiRange/MultiRange.stories.tsx
- src/components/MultiRange/MultiRange.tsx
Important note: values received in the onChange handler are not sorted, and should be sorted by the user of the multi range.
If we try to auto sort these values the user loses their grip on the drag handle when passing an other draghandle
> fix: allow multirange draghandles to overlap

- src/components/Icon/Icon.tsx
> fix: avoid empty icon name crash, render slash instead

- src/components/WYSIWYG/WYSIWYG.scss
https://district01.atlassian.net/browse/AVO2-743
> fix(wysiwyg): force list styles for ul and ol

- src/components/Thumbnail/Thumbnail.tsx
(Hopefully) fixes unwanted state updates on unmounted components 
Warning visible on search view in client:
> fix(thumbnail): clear possible state update in useEffect causing warning

- src/components/WYSIWYG/WYSIWYG.tsx
This caused issues with trumbowyg applying dom updates which didn't play well with React.
> fix(wysiwyg): trumbowyg instance never being destroyed

- src/components/TagList/TagList.scss
- src/components/TagList/TagList.stories.tsx
> fix(tag-list): avoid stretched close buttons

- src/content-blocks/BlockProjectsSpotlight/BlockProjectsSpotlight.mock.tsx
- src/content-blocks/BlockProjectsSpotlight/BlockProjectsSpotlight.stories.tsx
- src/content-blocks/BlockProjectsSpotlight/BlockProjectsSpotlight.test.tsx
- src/content-blocks/BlockProjectsSpotlight/BlockProjectsSpotlight.tsx
This is how the CTA and buttons block do it, this way we have to write less exceptions in the client
> fix(block-projects-spotlight): set navigate prop on each element

- src/components/Button/Button.tsx
- src/components/Table/Table.scss
- src/components/Table/Table.stories.tsx
- src/components/Table/Table.tsx
useful for when there are no multiple actions on a row, just one action to go to the detail of the clicked row item
> feat(table): add onTableClick option

- src/components/SearchResult/SearchResult.tsx
We use the truncate function in the client already, so if we use the lodash function in both places, it will save bytes
> fix(search-result): use lodash truncate instead of writing our own

- src/components/Container/Container.scss
- src/components/Container/Container.stories.tsx
- src/components/Container/Container.tsx
This will be helpful to use the full page, when showing overview tables in the admin dashboard:
current behavior:
behavior with full-width option:
> feat(container): add full width option for hor containers

- src/components/Select/Select.scss
This should fix the issue where buttons show up on top of the select dropdown menu:
> fix(select): increase z-index van dropdown list

- src/components/Select/Select.tsx
- src/components/TagsInput/TagsInput.stories.tsx
- src/components/TagsInput/TagsInput.tsx
The object passed to the onCreate handler was wrong, it should be the created tagOption.
Also fixed some issues with the story actions for tagInput
> fix(tag-input): fix issues when allowCreate is true, add translations

- src/components/KeyValueEditor/KeyValueEditor.tsx
This fixes the issue when you type something inside an existing string (not at the end of the string), then the textarea re-renders on every key press, causing your caret to jump to the end of the textarea.
> fix(key-value-editor): avoid cursor jumping to end of textarea on keyup

- src/components/SearchResult/SearchResult.stories.tsx
- src/components/SearchResult/SearchResult.tsx
needed when enabling searching for bundles
> fix(search-result): fix icons for collection and bundle types

- package-lock.json
- src/components/Accordion/Accordion.scss
- src/components/Accordion/Accordion.stories.tsx
closes: https://meemoo.atlassian.net/browse/AVO-174
|before|after|
|:---:|:---:|
|![image](https://user-images.githubusercontent.com/1710840/77636396-54458680-6f54-11ea-881d-43cf5268169a.png)|![image](https://user-images.githubusercontent.com/1710840/77636409-590a3a80-6f54-11ea-994e-84f6da34bd4d.png)|
> fix(accordion): ensure text is dark even when in dark container

- src/components/WYSIWYG/WYSIWYG.scss
- src/components/WYSIWYG/WYSIWYG.tsx
closes: https://meemoo.atlassian.net/browse/AVO-89
> fix(wysiwyg): add explanation for link target

- src/components/Table/Table.scss
wtf mono, why would you do this?
> fix(table): do not hide the border for the last row

- src/styles/components/_content.scss
related to: https://district01.atlassian.net/browse/AVO2-1050
seem like the fix added a colored border:
> fix(quote): remove colored border from quote

- src/content-blocks/BlockButtons/BlockButtons.tsx
fixes:
when adding a button block
> fix(buttons-block): add react key to each button

- src/components/Accordion/Accordion.tsx
this allows us to toggle accordions without passing the isOpen prop and use accordion slots at the same time.
> fix(accordion): also allow toggle self when we're using slots

- src/components/Modal/Modal.scss
part of: https://meemoo.atlassian.net/browse/AVO-109
This fixes the issue where a dropdown or date select control is cut off in a modal:
> fix(modal): ensure non scrollable modals are overflow visible

- src/content-blocks/BlockMediaList/BlockMediaList.mock.ts
- src/content-blocks/BlockMediaList/BlockMediaList.stories.tsx
- src/content-blocks/BlockMediaList/BlockMediaList.tsx
part of: https://meemoo.atlassian.net/browse/AVO-216
client PR twin: https://github.com/viaacode/avo2-client/pull/591
> feat(block-media-list): pass cta color params to cta block

- src/components/Header/Header.scss
- src/components/Header/Header.stories.tsx
- src/components/Header/Header.tsx
closes:
* https://meemoo.atlassian.net/browse/AVO-631
* https://meemoo.atlassian.net/browse/AVO-669
components:
This also fixes the issues in the client, without any changes needed in the client repo:
> fix(header): allow title to wrap when it is too long

- src/components/Toolbar/Toolbar.scss
part of: https://meemoo.atlassian.net/browse/AVO-669
> fix(toolbar): content items of toolbar should always be full width

- src/content-blocks/BlockGrid/BlockGrid.tsx
closes: https://meemoo.atlassian.net/browse/AVO-745
items do not duplicate anymore when toggling the title
> fix(page-overview-block): set better key for tiles in grid view

- src/components/Modal/Modal.scss
This caused the date-picker to not overflow visibly, now it will.
> fix(modal): overflow when scrollable

- src/components/Table/Table.stories.tsx
- src/components/Table/Table.tsx
part of: https://meemoo.atlassian.net/browse/AVO-836
Formatting of the "cell" content is still up to the consumer of this component using the renderCell function. So any padding can be added there
> feat(table): add option to show rows as cards, eg on mobile

- src/components/FlowPlayer/FlowPlayer.scss
|before|after|
|:---:|:---:|
|![image](https://user-images.githubusercontent.com/1710840/84263834-7d6fbf00-ab20-11ea-85e3-106dd53ebfb9.png)|![image](https://user-images.githubusercontent.com/1710840/84263839-7f398280-ab20-11ea-92ea-916c63489dc0.png)|
> fix(flowplayer): hide header when video is not yet playing

- src/components/Alert/Alert.scss
- src/components/Alert/Alert.stories.tsx
part of: https://meemoo.atlassian.net/browse/AVO-1190
|before|after|
|:---:|:---:|
|![image](https://user-images.githubusercontent.com/1710840/87144542-305e4480-c2a8-11ea-9c69-f7a1ebe81063.png)|![image](https://user-images.githubusercontent.com/1710840/87144547-33593500-c2a8-11ea-9686-b5d520ba4e9c.png)|
> fix(alert): remove top margin from heading if first elem in alert

- src/content-blocks/BlockImage/BlockImage.tsx
Resolves: https://meemoo.atlassian.net/browse/AVO-943
Enkel tonen indien de title property meegegeven is, as requested in ticket.
> AVO-943 block image copyright icon

- src/components/Toolbar/Toolbar.scss
closes: https://meemoo.atlassian.net/browse/AVO-354
toolbars should not have elevated z-index:
> fix(toolbar): remove mono fix that causes more issues than it solves

- src/components/FlowPlayer/FlowPlayer.scss
closes: https://meemoo.atlassian.net/browse/AVO-1067
to avoid nasty just from middle of trackbar to the start
before:
after:
> fix(flowplayer): fade in trackbar when video starts playing

- src/content-blocks/BlockImageGrid/BlockImageGrid.scss
- src/content-blocks/BlockImageGrid/BlockImageGrid.stories.tsx
- src/content-blocks/BlockImageGrid/BlockImageGrid.tsx
- src/content-blocks/BlockPageOverview/BlockPageOverview.tsx
- src/content-blocks/index.ts
part of: https://meemoo.atlassian.net/browse/AVO-188
also renamed block-grid to block-image-grid
> feat(block-image-grid): split align into align and text-align

- src/content-blocks/BlockSpotlight/BlockSpotlight.scss
closes: https://meemoo.atlassian.net/browse/AVO-714
desktop works correct:
mobile:
|before|after|
|:---:|:---:|
|![image](https://user-images.githubusercontent.com/1710840/91725741-72688000-eb9f-11ea-97ea-a4678e44adf0.png)|![image](https://user-images.githubusercontent.com/1710840/91725748-75637080-eb9f-11ea-9429-bcd8b35612f1.png)|
> fix(block-spotlight): give spotlight items a height on mobile

- src/components/Modal/Modal.tsx
When dragging from inside the modal to outside, the modal shouldn't close
This mainly happens when the modal has an input value that you want to select. For instance for the name of a collection:
> fix(modal): dont close when underlay was dragged instead of clicked

- src/content-blocks/BlockPageOverview/BlockPageOverview.scss
- src/content-blocks/BlockPageOverview/BlockPageOverview.stories.tsx
closes: https://meemoo.atlassian.net/browse/AVO-960
before:
after:
> fix(block-page-overview): center tabs inside flex center

- src/content-blocks/BlockRichText/BlockRichText.tsx
related to: https://meemoo.atlassian.net/browse/AVO-1290
|before|after|
|:---:|:---:|
|![image](https://user-images.githubusercontent.com/1710840/96025212-1d35b480-0e55-11eb-8cae-41d9f0f67c95.png)|![image](https://user-images.githubusercontent.com/1710840/96025218-1eff7800-0e55-11eb-96d5-10b39ee87fa6.png)|
> fix(block-rich-text): make each text column full width on mobile

- package-lock.json
- package.json
- src/components/CTA/CTA.mock.ts
- src/components/CTA/CTA.tsx
- src/components/MediaCard/MediaCard.tsx
- src/content-blocks/BlockAccordions/BlockAccordions.tsx
- src/content-blocks/BlockButtons/BlockButtons.stories.tsx
- src/content-blocks/BlockButtons/BlockButtons.test.tsx
- src/content-blocks/BlockButtons/BlockButtons.tsx
- src/content-blocks/BlockCTAs/BlockCTAs.mock.ts
- src/content-blocks/BlockCTAs/BlockCTAs.stories.tsx
- src/content-blocks/BlockCTAs/BlockCTAs.test.tsx
- src/content-blocks/BlockCTAs/BlockCTAs.tsx
- src/content-blocks/BlockHero/BlockHero.stories.tsx
- src/content-blocks/BlockHero/BlockHero.tsx
- src/content-blocks/BlockImageGrid/BlockImageGrid.stories.tsx
- src/content-blocks/BlockImageGrid/BlockImageGrid.tsx
- src/content-blocks/BlockMediaGrid/BlockMediaGrid.mock.ts
- src/content-blocks/BlockMediaGrid/BlockMediaGrid.stories.tsx
- src/content-blocks/BlockMediaGrid/BlockMediaGrid.test.tsx
- src/content-blocks/BlockMediaGrid/BlockMediaGrid.tsx
- src/content-blocks/BlockPageOverview/BlockPageOverview.stories.tsx
- src/content-blocks/BlockPageOverview/BlockPageOverview.tsx
- src/content-blocks/BlockRichText/BlockRichText.tsx
- src/content-blocks/BlockSpotlight/BlockSpotlight.scss
- src/content-blocks/BlockSpotlight/BlockSpotlight.stories.tsx
- src/content-blocks/BlockSpotlight/BlockSpotlight.test.tsx
- src/content-blocks/BlockSpotlight/BlockSpotlight.tsx
- src/helpers/render-link.tsx
- src/types/index.ts
partially closes: https://meemoo.atlassian.net/browse/AVO-1043
twin client PR: https://github.com/viaacode/avo2-client/pull/1084
so we can open links in new tab by right clicking the link/button
> feat(navigate): replace navigate by renderLink

- src/components/FlowPlayer/FlowPlayer.tsx
closes: https://meemoo.atlassian.net/browse/AVO-1416
avoid re-init flowplayer when url updates because the play ticket changed
|before|after|
|:---:|:---:|
|![image](https://user-images.githubusercontent.com/1710840/98004693-84111280-1df0-11eb-9d56-02eece7dced5.png)|![image](https://user-images.githubusercontent.com/1710840/98004680-81aeb880-1df0-11eb-9bc0-3a8d387d2ff3.png)|
> fix(flowplayer): avoid re-init when token of video changes

- src/components/Grid/Grid.scss
|before|after|
|:---:|:---:|
|![image](https://user-images.githubusercontent.com/1710840/98024099-212b7580-1e08-11eb-9fc3-dde6f69db63f.png)|![image](https://user-images.githubusercontent.com/1710840/98024104-22f53900-1e08-11eb-92e3-558b5a1b745c.png)|
> fix(grid): make columns 100% wide on mobile

- src/components/Menu/Menu.scss
part of: https://meemoo.atlassian.net/browse/AVO-1232
content from a dropdown menu could still occlude the mouse since it was only set to visible: hidden, but no pointer-events: none:
> fix(menu): disable hidden menu mouse interactions

- src/components/ImageGrid/ImageGrid.scss
- src/content-blocks/BlockImageGrid/BlockImageGrid.tsx
part of: https://meemoo.atlassian.net/browse/AVO-732
fix color and size of text in block-image-grid
> fix(block-image-grid): fix usp grid text size and color

- package-lock.json
- package.json
- src/components/Table/Table.tsx
The client currently has dataTypes like:
booolean
This stricter type will prevent that.
> fix(table): add stricter type for table column data type

- src/content-blocks/BlockPageOverview/BlockPageOverview.stories.tsx
- src/content-blocks/BlockPageOverview/BlockPageOverview.tsx
- src/content-blocks/BlockVideoTitleTextButton/BlockVideoTitleTextButton.tsx
part of: https://meemoo.atlassian.net/browse/AVO-1660
make labels in page overview items actual links instead of buttons with onClick handlers.
Can be tested in the storybook:
http://localhost:3020/?path=/story/blocks-blockpageoverview--blockpageoverview-show-date
> fix(block-page-overview): make label link buttons actual links

- src/components/DatePicker/DatePicker.stories.tsx
- src/components/DatePicker/DatePicker.tsx
closes: https://meemoo.atlassian.net/browse/AVO-1475
before: dates with "-" instead of "/" would be parsed as usa date format:
after: You can enter a date format with dashes:
when you press enter the date is parsed and the format is converted to "/"
when you click inside the input field again, the correct date is shown:
> fix(date-picker): avoid parsing date with wrong format as USA format

- src/components/Dropdown/Dropdown.scss
> fix(avo-1927): add margin to label next to icon inside dropdown trigger

- src/components/DatePicker/DatePicker.scss
https://meemoo.atlassian.net/browse/AVO-2142
before:
after:
> fix(avo-2142): fix time input field styling on firefox
