- src/components/WYSIWYG/WYSIWYG.css
- src/components/WYSIWYG/WYSIWYG.stories.tsx
> feat: improve visibility of the wysiwyg editor disabled state

- src/components/TagsInput/TagsInput.scss
closes: https://district01.atlassian.net/browse/AVO2-618
> fix: set tag input minheight instead of height

- src/components/Button/Button.scss
- src/components/Button/Button.stories.tsx
- src/components/Button/Button.tsx
> fix: allow disabled button with tooltip (title) attribute

- src/components/Form/Form.stories.tsx
- src/components/Form/FormGroup.scss
- src/components/Form/FormGroup.tsx
> feat: add required option to FormGroup element

- src/components/Button/Button.tsx
- src/components/ButtonGroup/ButtonGroup.scss
- src/components/ButtonGroup/ButtonGroup.stories.tsx
- src/components/ButtonGroup/ButtonGroup.test.tsx
- src/components/ButtonGroup/ButtonGroup.tsx
> feat: button-group component

- src/components/Thumbnail/Thumbnail.scss
- src/components/Thumbnail/Thumbnail.tsx
> fix(thumbnail): use css to center and cover thumbnail image

- src/components/Toolbar/Toolbar.stories.tsx
- src/components/Toolbar/Toolbar.tsx
> fix(toolbar): add justified option + allow use toolbar without slots

- src/components/TextInput/TextInput.stories.tsx
- src/components/TextInput/TextInput.tsx
needed for listening to enter key to parse entered time stamps for cutting a media fragment
> feat(text-input): add onKeyUp handler

- src/components/Modal/Modal.stories.tsx
- src/components/Modal/Modal.tsx
needed for login homepage => so users cannot redirect to home page from the login screen
> feat(modal): add option to have headless non-closeable modal

- src/components/Table/Table.stories.tsx
- src/components/Table/Table.test.tsx
- src/components/Table/Table.tsx
- src/index.ts
Fixes: https://github.com/viaacode/avo2-client/pull/237#discussion_r350205658
> refactor(table): rename type Column > TableColumn and add to index

- src/components/FlowPlayer/FlowPlayer.mock.tsx
- src/components/FlowPlayer/FlowPlayer.scss
- src/components/FlowPlayer/FlowPlayer.tsx
Passeerde toevallig aan deze code bij het implementeren van organizations dus heb even dit ticketje in de sprint getrokken aangezien het 5 minuten werk was.
> AVO2-391: Display organization logo on media fragment.

- src/components/Alert/Alert.scss
- src/components/Avatar/Avatar.tsx
- src/index.ts
> fix: export Accordion slots in main index

- src/components/HeaderContentType/HeaderContentType.tsx
- src/components/MediaCard/MediaCard.test.tsx
- src/components/Menu/MenuSearchResultContent/MenuSearchResultContent.tsx
- src/components/MetaData/MetaData.stories.tsx
- src/components/Thumbnail/Thumbnail.stories.tsx
- src/components/Thumbnail/Thumbnail.tsx
> fix(thumbnail): resolve bundle category to folder icon everwhere

- src/content-blocks/BlockIFrame/BlockIFrame.stories.tsx
- src/content-blocks/BlockIFrame/BlockIFrame.tsx
closes: https://district01.atlassian.net/browse/AVO2-967
> fix(block-iframe): add // prefix if not already present

- src/components/MultiRange/MultiRange.scss
- src/components/MultiRange/MultiRange.stories.tsx
- src/components/MultiRange/MultiRange.tsx
> feat(multi-range): add input field to multirange

- src/content-blocks/BlockProjectsSpotlight/BlockProjectsSpotlight.mock.tsx
- src/content-blocks/BlockProjectsSpotlight/BlockProjectsSpotlight.tsx
not every project has to have a link
> fix(project-spotlight-block): make buttonAction optional

- src/components/FlowPlayer/FlowPlayer.scss
- src/components/FlowPlayer/FlowPlayer.stories.tsx
- src/components/FlowPlayer/FlowPlayer.tsx
- src/styles/settings/_colors.scss
This works similar to the WYSIWYG component by using the shouldComponentUpdate lifecycle hook
> Bugfix: avoid multiple renders of the same flowplayer

- src/components/Table/Table.scss
- src/components/Table/Table.stories.tsx
- src/components/Table/Table.tsx
Required for bulk actions in the admin dashboard
Supported behavior:
* select rows by checking checkbox of the row
* select all rows by checking checkbox in title row
* click row to select row if no onRowClicked handler is defined
> feat(table): add checkbox column and onSelectionChange handler

- src/components/Table/Table.scss
- src/components/Table/Table.tsx
> fix(table): fix styling issue with table content

- src/components/Modal/Modal.scss
> fix(modal): make extra large modal wider

- src/components/CTA/CTA.stories.tsx
- src/components/CTA/CTA.tsx
- src/content-blocks/BlockCTAs/BlockCTAs.stories.tsx
- src/content-blocks/BlockCTAs/BlockCTAs.tsx
closes: https://meemoo.atlassian.net/browse/AVO-100
> fix(cta-block): allow passing a width property

- src/components/Accordion/Accordion.stories.tsx
- src/components/Accordion/Accordion.tsx
- src/components/Button/Button.scss
- src/components/ButtonToolbar/ButtonToolbar.scss
||
|:---:|
|before|
|![image](https://user-images.githubusercontent.com/1710840/78222470-97a87380-74c5-11ea-9239-843afaa98f0b.png)|
|after|
|![image](https://user-images.githubusercontent.com/1710840/78222583-c7577b80-74c5-11ea-84f7-918bfbd6accc.png)|
> fix(accordion): allow toggle accordion on title even with slots

- package-lock.json
- package.json
- src/components/SearchResult/SearchResult.test.tsx
- src/components/Select/Select.stories.tsx
- src/components/Select/Select.tsx
this is handy for adding a block from a dropdown, but the dropdown should always show the "add a block" placeholder
> fix(select): allow selected value to always remain null

- src/components/Flex/Flex.tsx
- src/components/WYSIWYG/WYSIWYG.stories.tsx
- src/content-blocks/BlockPageOverview/BlockPageOverview.scss
- src/content-blocks/BlockPageOverview/BlockPageOverview.stories.tsx
- src/content-blocks/BlockPageOverview/BlockPageOverview.tsx
- src/types/index.ts
part of: https://meemoo.atlassian.net/browse/AVO-238
> fix(page-overview-block): center tabs + add option for header bg color

- src/components/CTA/CTA.tsx
- src/components/Spacer/Spacer.tsx
- src/components/WYSIWYG/WYSIWYG.scss
- src/content-blocks/BlockCTAs/BlockCTAs.mock.ts
- src/content-blocks/BlockCTAs/BlockCTAs.tsx
- src/content-blocks/BlockHeading/BlockHeading.tsx
- src/content-blocks/BlockRichText/BlockRichText.tsx
- src/types/index.ts
part of: https://meemoo.atlassian.net/browse/AVO-216
> feat(cta): expose more options: colors for title, content and bg

- src/content-blocks/BlockGrid/BlockGrid.scss
- src/content-blocks/BlockGrid/BlockGrid.stories.tsx
- src/content-blocks/BlockGrid/BlockGrid.tsx
add navigation test for grid block and add optional button
> fix(block-grid): add link and button to block image grid

- src/types/index.ts
part of: https://meemoo.atlassian.net/browse/AVO-265
> fix(types): add link target enum type to ButtonAction

- src/components/Button/Button.scss
- src/components/Button/Button.stories.tsx
- src/components/Button/Button.tsx
> feat(button): add large option to match height of select

- src/content-blocks/BlockSpotlight/BlockSpotlight.tsx
It slipped through our defences. :(
> fix: console.log

- src/components/KeyValueEditor/KeyValueEditor.stories.tsx
- src/components/KeyValueEditor/KeyValueEditor.test.tsx
- src/components/KeyValueEditor/KeyValueEditor.tsx
closes: https://meemoo.atlassian.net/browse/AVO-320
client twin PR: https://github.com/viaacode/avo2-client/pull/569
> fix(key-value-editor): keep row visible when searching and modifying val

- src/components/WYSIWYG/WYSIWYG.scss
- src/components/WYSIWYG/WYSIWYG.stories.tsx
- src/components/WYSIWYG/WYSIWYG.tsx
closes: https://meemoo.atlassian.net/browse/AVO-91
Fix table dropdown style + blue highlight :D
Fix scrollbar on windows for table options:
Fix link target styles:
Add simple link option:
> fix(wysiwyg): fix table styles, fix link styles, add minimal link option

- src/components/Container/Container.tsx
- src/content-blocks/BlockImage/BlockImage.scss
- src/content-blocks/BlockImage/BlockImage.stories.tsx
- src/content-blocks/BlockImage/BlockImage.tsx
closes: 
* https://meemoo.atlassian.net/browse/AVO-572
* https://meemoo.atlassian.net/browse/AVO-601
client twin PR: https://github.com/viaacode/avo2-client/pull/568
> feat(image-block): add full-width and page-header sizes and align option

- src/components/Button/Button-skins.scss
- src/components/Button/Button.types.ts
- src/content-blocks/BlockButtons/BlockButtons.mock.ts
- src/content-blocks/BlockButtons/BlockButtons.stories.tsx
- src/content-blocks/BlockButtons/BlockButtons.tsx
- src/types/index.ts
closes:
* https://meemoo.atlassian.net/browse/AVO-330
* https://meemoo.atlassian.net/browse/AVO-331
Client PR: https://github.com/viaacode/avo2-client/pull/572
> feat(anchor-links): fix divider + move navigate to block level

- src/components/Table/Table.stories.tsx
- src/components/Table/Table.tsx
part of: https://meemoo.atlassian.net/browse/AVO-289
> feat(table): add icons in the column headers

- src/components/Avatar/Avatar.scss
- src/components/Avatar/Avatar.stories.tsx
Foto's worden niet meer uitgerokken in avatar's.
> feat(avatar): image cover

- src/components/FlowPlayer/FlowPlayer.tsx
closes: https://meemoo.atlassian.net/browse/AVO-614
> fix(flowplayer): also rerender when post url changes

- src/components/FlowPlayer/FlowPlayer.tsx
part of:
* https://meemoo.atlassian.net/browse/AVO-605
* https://meemoo.atlassian.net/browse/AVO-606
client PR twin:
> fix(flowplayer): pause flowplayer when modal opens / closes

- src/content-blocks/BlockPageOverview/BlockPageOverview.stories.tsx
- src/content-blocks/BlockPageOverview/BlockPageOverview.tsx
part of https://meemoo.atlassian.net/browse/AVO-652
client PR: https://github.com/viaacode/avo2-client/pull/597
> fix(page-overview): header background color will be set in client

- package-lock.json
- package.json
- src/components/Header/Header.scss
- src/components/Header/Header.tsx
- src/components/Modal/Modal.scss
closes: https://meemoo.atlassian.net/browse/AVO-339
also fixed a header css bug
> fix(modal): avoid scaling modal when opening so slider inits correctly

- src/components/MetaData/MetaDataItem/MetaDataItem.tsx
- src/components/Thumbnail/Thumbnail.tsx
- src/content-blocks/BlockMediaList/BlockMediaList.mock.ts
- src/content-blocks/BlockMediaList/BlockMediaList.scss
- src/content-blocks/BlockMediaList/BlockMediaList.stories.tsx
- src/content-blocks/BlockMediaList/BlockMediaList.tsx
part of: https://meemoo.atlassian.net/browse/AVO-609
related client PR: https://github.com/viaacode/avo2-client/pull/620
> fix(media-tile-block): rework layout cta block

- src/components/Accordion/Accordion.scss
- src/content-blocks/BlockHeading/BlockHeading.tsx
- src/content-blocks/BlockImage/BlockImage.scss
- src/content-blocks/BlockImage/BlockImage.tsx
- src/content-blocks/BlockPageOverview/BlockPageOverview.stories.tsx
- src/content-blocks/BlockPageOverview/BlockPageOverview.tsx
- src/content-blocks/BlockRichText/BlockRichText.scss
- src/content-blocks/BlockRichText/BlockRichText.tsx
part of: https://meemoo.atlassian.net/browse/AVO-315
client pr: https://github.com/viaacode/avo2-client/pull/636
> fix(blocks): remove margin on block content, block will handle margin

- src/content-blocks/BlockImage/BlockImage.scss
- src/content-blocks/BlockImage/BlockImage.stories.tsx
- src/content-blocks/BlockImage/BlockImage.tsx
part of: https://meemoo.atlassian.net/browse/AVO-746
client PR: https://github.com/viaacode/avo2-client/pull/674
> fix(image-block): show annotation for page header images

- src/content-blocks/BlockIntro/BlockIntro.stories.tsx
- src/content-blocks/BlockIntro/BlockIntro.tsx
- src/content-blocks/BlockRichText/BlockRichText.tsx
Heading type toevoegen want op collectie-pagina's moet dit een h3 worden.
> feat(intro): add headingType prop

- src/components/WYSIWYG2/WYSIWYG2.tsx
- src/components/index.ts
so we don't make any typo's in the client if we're going to have more custom toolbars
> fix(RTE): add stricter type for RTE controls

- src/content-blocks/BlockButtons/BlockButtons.scss
- src/content-blocks/BlockButtons/BlockButtons.tsx
closes: https://meemoo.atlassian.net/browse/AVO-743
|before|after|
|:---:|:---:|
|![image](https://user-images.githubusercontent.com/1710840/82204275-e5a5f900-9904-11ea-9fa4-ea45d8be7e70.png)|![image](https://user-images.githubusercontent.com/1710840/82204285-e8a0e980-9904-11ea-94d0-a1cff073ad71.png)|
> fix(anchor-links-block): reduce padding from buttons and dividers

- src/components/WYSIWYG2/WYSIWYG2.stories.tsx
- src/components/WYSIWYG2/WYSIWYG2.tsx
closes: https://meemoo.atlassian.net/browse/AVO-787
> fix(wysiwyg): correctly interpret tables in initialHTML

- src/components/FlowPlayer/FlowPlayer.scss
closes: https://meemoo.atlassian.net/browse/AVO-373
|before|after|
|:---:|:---:|
|![image](https://user-images.githubusercontent.com/1710840/83549088-0a08f480-a505-11ea-8a7c-df2fa096ed45.png)|![image](https://user-images.githubusercontent.com/1710840/83553978-5b68b200-a50c-11ea-85d9-efd6c885896e.png)|
> fix(flowplayer): vertically center play button

- src/content-blocks/BlockPageOverview/BlockPageOverview.stories.tsx
- src/content-blocks/BlockPageOverview/BlockPageOverview.tsx
part of: https://meemoo.atlassian.net/browse/AVO-661
> feat(page-overview-block): open accordion if activePageId is set

- src/components/Quote/Quote.tsx
- src/content-blocks/BlockIntro/BlockIntro.stories.tsx
- src/content-blocks/BlockIntro/BlockIntro.tsx
- src/content-blocks/BlockQuote/BlockQuote.stories.tsx
part of: https://meemoo.atlassian.net/browse/AVO-315
> Fix: Remove padding from block content components

- src/components/Icon/Icon.scss
- src/components/Quote/Quote.scss
closes: https://meemoo.atlassian.net/browse/AVO-811
> feat(quote): double avatar size

- src/components/Checkbox/Checkbox.tsx
part of: https://meemoo.atlassian.net/browse/AVO-689
> feat(checkbox): allow label to be react node

- package-lock.json
- package.json
- src/components/Button/Button-skins.scss
- src/components/Button/Button.stories.tsx
- src/components/Button/Button.types.ts
closes: https://meemoo.atlassian.net/browse/AVO-773
> feat(button): add yellow button styles

- package-lock.json
- package.json
- src/components/FlowPlayer/FlowPlayer.scss
- src/components/FlowPlayer/FlowPlayer.stories.tsx
- src/components/FlowPlayer/FlowPlayer.tsx
part of: https://meemoo.atlassian.net/browse/AVO-194
> fix(flowplayer): enable cuepoints on the trackbar

- src/components/CTA/CTA.tsx
- src/content-blocks/BlockHero/BlockHero.scss
- src/content-blocks/BlockHero/BlockHero.stories.tsx
- src/content-blocks/BlockHero/BlockHero.test.tsx
- src/content-blocks/BlockHero/BlockHero.tsx
- src/content-blocks/BlockRichText/BlockRichText.tsx
- src/content-blocks/index.ts
part of: https://meemoo.atlassian.net/browse/AVO-771
> fix(block-hero): add hero block

- src/content-blocks/BlockPageOverview/BlockPageOverview.tsx
part of: https://meemoo.atlassian.net/browse/AVO-804
> fix(page-overview): hide categories when they do not have labels

- src/components/WYSIWYG2/WYSIWYG2.scss
part of:
* https://meemoo.atlassian.net/browse/AVO-864
* https://meemoo.atlassian.net/browse/AVO-863
> fix(wysiwyg2): add margin to RTE line divs

- src/components/Button/Button.types.ts
part of: https://meemoo.atlassian.net/browse/AVO-773
> feat(button-types): add underlined pupil button type

- src/content-blocks/BlockGrid/BlockGrid.tsx
- src/content-blocks/BlockPageOverview/BlockPageOverview.mock.ts
- src/content-blocks/BlockPageOverview/BlockPageOverview.tsx
part of: https://meemoo.atlassian.net/browse/AVO-841
|before|after|
|:---:|:---:|
|![image](https://user-images.githubusercontent.com/1710840/83857019-ac4df580-a71a-11ea-9212-16b412702f8a.png)|![image](https://user-images.githubusercontent.com/1710840/83857031-aeb04f80-a71a-11ea-84fd-d5ca63d9f565.png)|
> fix(page-overview): render html in page description

- src/components/AspectRatioWrapper/AspectRatioWrapper.tsx
- src/components/FlowPlayer/FlowPlayer.scss
- src/components/FlowPlayer/FlowPlayer.stories.tsx
- src/components/FlowPlayer/FlowPlayer.tsx
> fix(flowplayer): make thumbnail cover entire video

- src/components/WYSIWYG2/WYSIWYG2.scss
closes: https://meemoo.atlassian.net/browse/AVO-862
|before|after|
|:---:|:---:|
|![image](https://user-images.githubusercontent.com/1710840/84015733-96d80600-a97c-11ea-955c-089d000db80d.png)|![image](https://user-images.githubusercontent.com/1710840/84015741-99d2f680-a97c-11ea-81aa-956211e77668.png)|
> fix(wysiwyg2): fix line breaks inside RTE

- src/components/FlowPlayer/FlowPlayer.scss
- src/components/FlowPlayer/FlowPlayer.tsx
- src/content-blocks/BlockHero/BlockHero.tsx
closes: https://meemoo.atlassian.net/browse/AVO-893
handige branch om dit te testen in de client: `temp/flowplayer-and-hero-in-client`
> AVO-893 Content block 'hero': eigen video speelt niet af / poster wordt niet getoond

- src/content-blocks/BlockHero/BlockHero.stories.tsx
- src/content-blocks/BlockHero/BlockHero.tsx
part of: https://meemoo.atlassian.net/browse/AVO-927
> feat(hero-block): add rich text below buttons

- src/components/Button/Button-skins.scss
- src/components/Button/Button.stories.tsx
Closes https://meemoo.atlassian.net/browse/AVO-901
> fix(buttons): pupil underlined link color

- src/content-blocks/BlockMediaList/BlockMediaList.mock.ts
- src/content-blocks/BlockMediaList/BlockMediaList.scss
- src/content-blocks/BlockMediaList/BlockMediaList.stories.tsx
- src/content-blocks/BlockMediaList/BlockMediaList.tsx
closes: https://meemoo.atlassian.net/browse/AVO-819
> AVO-819 Content Block 'Media tegels': plaatsing knop CTA-tegel dynamisch maken + tekst onder image

- package-lock.json
- src/components/FlowPlayer/FlowPlayer.stories.tsx
- src/components/FlowPlayer/FlowPlayer.tsx
Closes: https://meemoo.atlassian.net/browse/AVO-892
> fix(flowplayer): pause on cuepoint end

- src/components/FlowPlayer/FlowPlayer.mock.tsx
- src/components/FlowPlayer/FlowPlayer.scss
- src/components/FlowPlayer/FlowPlayer.stories.tsx
- src/components/FlowPlayer/FlowPlayer.test.tsx
- src/content-blocks/BlockMediaList/BlockMediaList.mock.ts
- src/content-blocks/BlockMediaList/BlockMediaList.stories.tsx
- src/content-blocks/BlockMediaList/BlockMediaList.tsx
part of: https://meemoo.atlassian.net/browse/AVO-969
client PR: https://github.com/viaacode/avo2-client/pull/819
> AVO-969 KLAAR pagina en archief: zichtbaarheid filmpjes uit MAM niet in orde wanneer niet aangemeld

- src/components/FlowPlayer/FlowPlayer.scss
Closes: https://meemoo.atlassian.net/browse/AVO-1050
Toont altijd ipv op "is-starting" wat de flowplayer thumbnail mode is, die je dus enkel hebt non-item videos.
> AVO-1050: flowplayer logo

- src/content-blocks/BlockMediaList/BlockMediaList.mock.ts
- src/content-blocks/BlockMediaList/BlockMediaList.stories.tsx
- src/content-blocks/BlockMediaList/BlockMediaList.tsx
Closes: https://meemoo.atlassian.net/browse/AVO-1077
Nu wordt de juiste button action meegegeven. Took 17 decades to find, 1 second to fix. 😅
> fix(media-list): action

- src/components/Thumbnail/Thumbnail.tsx
- src/content-blocks/BlockMediaList/BlockMediaList.mock.ts
- src/content-blocks/BlockMediaList/BlockMediaList.tsx
part of: https://meemoo.atlassian.net/browse/AVO-1077
> fix(media-tile-block): split button action from tile action

- src/components/MediaCard/MediaCard.scss
- src/components/Thumbnail/Thumbnail.scss
- src/content-blocks/BlockMediaList/BlockMediaList.scss
- src/content-blocks/BlockMediaList/BlockMediaList.tsx
> fix(media-list): fix cta block

- package-lock.json
- package.json
- src/content-blocks/BlockCTAs/BlockCTAs.mock.ts
- src/content-blocks/BlockCTAs/BlockCTAs.tsx
closes: https://meemoo.atlassian.net/browse/AVO-1126
test page: http://localhost:8080/beheer/content/379
> fix(block-cta): correctly pass navigate function to cta components

- src/content-blocks/BlockRichText/BlockRichText.scss
- src/content-blocks/BlockRichText/BlockRichText.stories.tsx
- src/content-blocks/BlockRichText/BlockRichText.tsx
part of: https://meemoo.atlassian.net/browse/AVO-868
> feat(rich-text-block): add maxTextWidth option

- src/components/Tabs/Tab/Tab.scss
- src/components/Tabs/Tab/Tab.test.tsx
- src/components/Tabs/Tab/Tab.tsx
- src/components/Tabs/Tabs.scss
- src/components/Tabs/Tabs.stories.tsx
- src/components/Tabs/Tabs.test.tsx
- src/components/Tabs/Tabs.tsx
- src/content-blocks/BlockPageOverview/BlockPageOverview.stories.tsx
- src/content-blocks/BlockPageOverview/BlockPageOverview.tsx
- src/styles/settings/_colors.scss
closes: https://meemoo.atlassian.net/browse/AVO-900
twin client PR: https://github.com/viaacode/avo2-client/pull/889
> fix(tabs): add dark option for tabs and page overview header

- src/content-blocks/BlockHero/BlockHero.scss
- src/content-blocks/BlockHero/BlockHero.tsx
closes: https://meemoo.atlassian.net/browse/AVO-894
prototype:
hero in client:
|before|after|
|:---:|:---:|
|![image](https://user-images.githubusercontent.com/1710840/87043568-81f9c700-c1f5-11ea-8d89-8c4db787d619.png)|![image](https://user-images.githubusercontent.com/1710840/87043599-8de58900-c1f5-11ea-8e08-0bf538f9870a.png)|
> fix(hero-block): remove margin around hero width, add margin-top mobile

- src/content-blocks/BlockPageOverview/BlockPageOverview.scss
- src/content-blocks/BlockPageOverview/BlockPageOverview.tsx
closes: https://meemoo.atlassian.net/browse/AVO-946
> fix(page-overview-block): change padding items according to prototype

- src/content-blocks/BlockMediaList/BlockMediaList.tsx
closes: https://meemoo.atlassian.net/browse/AVO-969
> fix(block-media-list): correctly open media items in modal

- src/content-blocks/BlockPageOverview/BlockPageOverview.tsx
part of: https://meemoo.atlassian.net/browse/AVO-1142
> fix(page-overview-block): format date using moment and nl locale

- package-lock.json
- src/components/Thumbnail/Thumbnail.scss
- src/components/Thumbnail/Thumbnail.stories.tsx
- src/components/Thumbnail/Thumbnail.tsx
Necessary for https://meemoo.atlassian.net/browse/AVO-326
> fix(thumbnail): allow only showing category icon

- src/components/Table/Table.tsx
part of: https://meemoo.atlassian.net/browse/AVO-810
steps:
* select multiple collection rows
* change owner
* try to deselect a row
expected result: row is deselected
current result: row remains selected
> fix(table): allow deselection of rows for bulk actions

- src/content-blocks/BlockPageOverview/BlockPageOverview.tsx
closes: https://meemoo.atlassian.net/browse/AVO-945
> feat(page-overview): show news overview imgs using aspect ratio cover

- package-lock.json
- package.json
- src/components/Modal/Modal.stories.tsx
- src/components/Modal/Modal.tsx
closes: https://meemoo.atlassian.net/browse/AVO-1076
also stops event propagation when scrolling modal body to main document scroll
> fix(modal): use custom scrollbar to avoid jitter issue on windows

- src/content-blocks/BlockHero/BlockHero.scss
- src/content-blocks/BlockIFrame/BlockIFrame.scss
- src/content-blocks/BlockIFrame/BlockIFrame.stories.tsx
- src/content-blocks/BlockIFrame/BlockIFrame.tsx
part of: https://meemoo.atlassian.net/browse/AVO-1239
iframe:
hero:
> fix(blocks): add border-radius to iframe and hero blocks

- src/components/MultiRange/MultiRange.tsx
part of: https://meemoo.atlassian.net/browse/AVO-1010
has a corresponding client PR:
> fix(multi-range): improve drag behavior + text input behavior

- src/components/Modal/Modal.tsx
part of: https://meemoo.atlassian.net/browse/AVO-1285
closed modal:
open modal:
> feat(modal): add class to body while modal is open

- src/components/FlowPlayer/FlowPlayer.scss
- src/components/FlowPlayer/FlowPlayer.stories.tsx
closes: https://meemoo.atlassian.net/browse/AVO-1067
|before|after|
|:---:|:---:|
|![image](https://user-images.githubusercontent.com/1710840/90633501-6fc46d00-e226-11ea-8025-549a5fe5982f.png)|![image](https://user-images.githubusercontent.com/1710840/90633511-72bf5d80-e226-11ea-8b03-7f30ad0d6c8d.png)|
> fix(flowplayer): improve control bar styles

- src/content-blocks/BlockPageOverview/BlockPageOverview.tsx
closes: https://meemoo.atlassian.net/browse/AVO-945
news list
project list
> feat(page-overview): custom aspect ratio for newslist images

- src/components/Modal/Modal.scss
part of: https://meemoo.atlassian.net/browse/AVO-1316
> fix(modal): disable pointer events for closed modals

- src/components/Button/Button.scss
part of: https://meemoo.atlassian.net/browse/AVO-991
> fix(button): allow button wrap when autoHeight = true

- src/components/Button/Button.scss
closes: https://meemoo.atlassian.net/browse/AVO-777
|before|after|
|:---:|:---:|
|![image](https://user-images.githubusercontent.com/1710840/92145335-5a4f6580-ee18-11ea-8b85-1d0991359636.png)|![image](https://user-images.githubusercontent.com/1710840/92145347-5facb000-ee18-11ea-9248-67759a0074eb.png)|
> fix(button): fix button cutoff mono styles

- src/components/FlowPlayer/FlowPlayer.tsx
closes: https://meemoo.atlassian.net/browse/AVO-1267
@benjaminnaesen test je deze ook ff op je mac in safari. De flowplayer geknipt story in de components moet beginnen met spelen op 1:00 ipv 0:00
> fix(flowplayer): set cue startpoint after flowplayer started playing

- src/components/Toolbar/Toolbar.scss
- src/components/Toolbar/Toolbar.tsx
part of: https://meemoo.atlassian.net/browse/AVO-1019
> fix(toolbar): add option to wrap items below eachother

- src/components/Modal/Modal.scss
part of: https://meemoo.atlassian.net/browse/AVO-580
|before|after|
|:---:|:---:|
|![image](https://user-images.githubusercontent.com/1710840/92504145-86952880-f202-11ea-86d2-c250716c1a38.png)|![image](https://user-images.githubusercontent.com/1710840/92504147-885eec00-f202-11ea-9fdd-cd5c15815c21.png)|
> fix(modal): reduce modal height to 100% - 40px

- package-lock.json
- package.json
- src/content-blocks/BlockSpotlight/BlockSpotlight.scss
closes: https://meemoo.atlassian.net/browse/AVO-714
|before|after|
|:---:|:---:|
|![image](https://user-images.githubusercontent.com/1710840/92617942-206edb00-f2c0-11ea-940b-9e9472569f1c.png)|![image](https://user-images.githubusercontent.com/1710840/92618000-3086ba80-f2c0-11ea-9768-9c5ae31f13c1.png)|
> Fix spotlight height on mobile

- src/components/Container/Container.scss
- src/components/FlowPlayer/FlowPlayer.mock.tsx
- src/components/FlowPlayer/FlowPlayer.stories.tsx
- src/components/FlowPlayer/FlowPlayer.tsx
- src/components/index.ts
part of: https://meemoo.atlassian.net/browse/AVO-468
skip to video position: 01:20
requires proxy to be running to convert subtitles from srt to vtt
> feat(flowplayer): add subtitle support

- src/components/FlowPlayer/FlowPlayer.scss
closes: https://meemoo.atlassian.net/browse/AVO-1397
> fix(flowplayer): fix flowplayer fullscreen on safari

- src/content-blocks/BlockPageOverview/BlockPageOverview.tsx
closes: meemoo.atlassian.net/browse/AVO-1394
> fix(block-page-overview): show day of month instead of day of week

- src/components/Quote/Quote.scss
- src/content-blocks/BlockPageOverview/BlockPageOverview.tsx
- src/content-blocks/BlockQuote/BlockQuote.scss
- src/content-blocks/BlockQuote/BlockQuote.tsx
part of: https://meemoo.atlassian.net/browse/AVO-1290
|before|after|
|:---:|:---:|
|![image](https://user-images.githubusercontent.com/1710840/96271323-0619d280-0fcd-11eb-86c6-1235ad297fa0.png)|![image](https://user-images.githubusercontent.com/1710840/96271333-0914c300-0fcd-11eb-842a-9a3da01f633d.png)|
> fix(block-quote): avoid stretching the avatar circle + add mobile margin

- src/types/index.ts
part of: https://meemoo.atlassian.net/browse/AVO-882
> feat(types): add FILE option to content picker types

- src/components/Grid/Grid.scss
- src/content-blocks/BlockMediaGrid/BlockMediaGrid.stories.tsx
closes: https://meemoo.atlassian.net/browse/AVO-1078
|before|after|
|:---:|:---:|
|![image](https://user-images.githubusercontent.com/1710840/96576039-da029800-12d1-11eb-9c61-82003696ec52.png)|![image](https://user-images.githubusercontent.com/1710840/96576050-de2eb580-12d1-11eb-979e-4672a2cc7581.png)|
> feat(grid): make all columns the same width regardless of free space

- src/content-blocks/BlockSpotlight/BlockSpotlight.scss
- src/content-blocks/BlockSpotlight/BlockSpotlight.tsx
closes: https://meemoo.atlassian.net/browse/AVO-951
> feat(block-spotlight): add chevron icon after title

- src/components/Table/Table.stories.tsx
- src/components/Table/Table.tsx
part of: https://meemoo.atlassian.net/browse/AVO-1342
clientPR: https://github.com/viaacode/avo2-client/pull/1092
> feat(table): switch select all rows to handler instead of select page

- src/components/Accordion/Accordion.scss
- src/components/Toolbar/Toolbar.scss
part of: https://meemoo.atlassian.net/browse/AVO-115
|before|after|
|:---:|:---:|
|![image](https://user-images.githubusercontent.com/1710840/97855351-e7207d80-1cfa-11eb-9fc7-cfbb411ddfd6.png)|![image](https://user-images.githubusercontent.com/1710840/97855361-e982d780-1cfa-11eb-8c08-fe978246284c.png)|
> fix(toolbar): set min-height instead of height

- src/components/Tooltip/Tooltip.stories.tsx
- src/components/Tooltip/Tooltip.tsx
fixes issue where the tooltip would not hide anymore:
> tooltip hide issue

- src/components/ImageGrid/ImageGrid.tsx
- src/components/Tooltip/Tooltip.tsx
- src/content-blocks/BlockImageGrid/BlockImageGrid.scss
- src/content-blocks/BlockImageGrid/BlockImageGrid.stories.tsx
- src/content-blocks/BlockImageGrid/BlockImageGrid.tsx
part of: https://meemoo.atlassian.net/browse/AVO-732
text size, weight, and margin
horizontal margin:
vertical margin
> feat(image-grid-block): add some text and margin options

- src/components/Button/Button-skins.scss
- src/components/MediaCard/MediaCard.scss
- src/components/SearchResult/SearchResult.scss
- src/content-blocks/BlockMediaGrid/BlockMediaGrid.scss
closes: https://meemoo.atlassian.net/browse/AVO-1228
> feat(links): make link underlining more consistent

- src/content-blocks/BlockEventbrite/BlockEventbrite.scss
- src/content-blocks/BlockEventbrite/BlockEventbrite.stories.tsx
- src/content-blocks/BlockEventbrite/BlockEventbrite.tsx
part of: https://meemoo.atlassian.net/browse/AVO-451
> feat(eventbrite): add align option

- src/components/Avatar/Avatar.scss
- src/components/FlowPlayer/FlowPlayer.test.tsx
part of: https://meemoo.atlassian.net/browse/AVO-1290
|before|after|
|:---:|:---:|
|![image](https://user-images.githubusercontent.com/1710840/99666475-58865d00-2a6b-11eb-859d-8bfadb342bb0.png)|![image](https://user-images.githubusercontent.com/1710840/99666509-61772e80-2a6b-11eb-9add-f146683fd0e3.png)|
> fix(avatar): allow avatar text to wrap

- src/content-blocks/BlockImage/BlockImage.scss
part of: https://meemoo.atlassian.net/browse/AVO-1290
> fix(block-image): add css rule to make max-width of images 100%

- src/components/MediaCard/MediaCard.scss
closes: https://meemoo.atlassian.net/browse/AVO-1228
> fix(media-grid): fix title hover underline behavior

- package-lock.json
- package.json
- src/components/CTA/CTA.tsx
- src/content-blocks/BlockButtons/BlockButtons.tsx
- src/content-blocks/BlockHero/BlockHero.tsx
- src/content-blocks/BlockImageGrid/BlockImageGrid.tsx
- src/content-blocks/BlockMediaGrid/BlockMediaGrid.tsx
- src/content-blocks/BlockPageOverview/BlockPageOverview.tsx
- src/content-blocks/BlockRichText/BlockRichText.tsx
- src/content-blocks/BlockSpotlight/BlockSpotlight.tsx
- src/helpers/render-link.tsx
- src/types/index.ts
part of: https://meemoo.atlassian.net/browse/AVO-1471
> Add labels to renderLinkFunction

- src/components/Button/Button.tsx
- src/components/Tooltip/Tooltip.scss
- src/content-blocks/BlockButtons/BlockButtons.scss
part of: https://meemoo.atlassian.net/browse/AVO-882
Change tooltip colors
> feat(tooltip): change tooltip colors

- src/components/FlowPlayer/FlowPlayer.stories.tsx
- src/components/Modal/Modal.scss
- src/components/Modal/Modal.tsx
- src/helpers/index.ts
closes: https://meemoo.atlassian.net/browse/AVO-1522
> fix(flowplayer): remove transforms on modal since flowplayer breaks

- src/components/MediaCard/MediaCard.scss
- src/components/Thumbnail/Thumbnail.scss
closes: https://meemoo.atlassian.net/browse/AVO-1580
before:
after:
> fix(media-card): hide label and ellipsis titles

- src/components/Button/Button.scss
closes: https://meemoo.atlassian.net/browse/AVO-1525
> fix(button): add pointer-events none to button icon

- src/components/Table/Table.tsx
Added a type to `Table.tsx` for `temp_access` sorting
DEV-1704
https://meemoo.atlassian.net/jira/software/c/projects/AVO/boards/32?modal=detail&selectedIssue=DEV-1704
Client
viaacode/avo2-client#1275
Proxy
https://github.com/viaacode/avo2-proxy/pull/388
> feat: add temp_access sort edge case type

- src/components/FlowPlayer/FlowPlayer.tsx
trigger ended event on end cuepoint
> fix(avo-1724): trigger ended event on end cuepoint

- src/components/Dropdown/Dropdown.tsx
> fix(avo-1927): pass buttonType to dropdown

- package.json
- src/content-blocks/BlockMediaGrid/BlockMediaGrid.mock.ts
- src/content-blocks/BlockMediaGrid/BlockMediaGrid.stories.tsx
- src/content-blocks/BlockMediaGrid/BlockMediaGrid.tsx
https://meemoo.atlassian.net/browse/AVO-1722
This PR is required for this client PR: 
So we have more control in the client to show bookmark buttons and the like
> feat(avo-1722): make modal to play items external to the block

- src/components/WYSIWYG/WYSIWYG.scss
> fix(avo-1900): make rte more standalone

- package-lock.json
- package.json
- src/components/Button/Button.module.scss
- src/components/Button/Button.tsx
https://meemoo.atlassian.net/browse/ARC-1307
part of a group of PR's:
* https://github.com/viaacode/hetarchief-client/pull/844
* https://github.com/viaacode/react-admin-core-module/pull/169
* https://github.com/viaacode/avo2-components/pull/525
tekst left:
tekst right:
> Feat(ARC-1307): Title text button background image block

- src/components/Thumbnail/Thumbnail.tsx
- src/styles/components/_content-type.scss
- src/types/content-type.ts
Ticket: https://meemoo.atlassian.net/browse/AVO-2608
> feat(avo-2608): added assignment to content type

- src/components/Tabs/Tab/Tab.scss
[AVO-2619](https://meemoo.atlassian.net/browse/AVO-2619)
Before:
After:
[AVO-2619]: https://meemoo.atlassian.net/browse/AVO-2619?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(avo-2619): Add padding to tabs

- src/components/Header/Header.tsx
[AVO-2646](https://meemoo.atlassian.net/browse/AVO-2646)
[AVO-2647](https://meemoo.atlassian.net/browse/AVO-2647)
[Avo2-client PR](https://github.com/viaacode/avo2-client/pull/1778)
[AVO-2646]: https://meemoo.atlassian.net/browse/AVO-2646?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[AVO-2647]: https://meemoo.atlassian.net/browse/AVO-2647?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(avo-2646): Add the possibility to  insert a react node as title in header component

- src/components/SearchResult/SearchResult.tsx
- src/components/Thumbnail/Thumbnail.scss
- src/components/Thumbnail/Thumbnail.tsx
- src/components/Tooltip/Tooltip.scss
[AVO-2636](https://meemoo.atlassian.net/browse/AVO-2636)
[Avo2-typings PR](https://github.com/viaacode/avo2-typings/pull/123)
[Avo2-client PR](https://github.com/viaacode/avo2-client/pull/1784)
[AVO-2636]: https://meemoo.atlassian.net/browse/AVO-2636?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(avo-2636): Add tooltip to search result date, fix tooltip arrow when shown on the right side

- package-lock.json
- package.json
Described in https://github.com/vercel/turbo/issues/1769
> fix: add missing devDependency for apple CPU's

- src/components/Modal/Modal.scss
- src/components/Modal/Modal.slots.tsx
- src/components/Modal/Modal.test.tsx
- src/components/Modal/Modal.tsx
- src/components/index.ts
- src/setupTests.ts
- Add property to add a class to the html page itself (to disable scrolling of the entire page)
- Add new Modal component for a Subheader. In case we need a part of the content staying at the top of a scrollable modal
-
> #AVO-3639: Modal changes
